apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pilotedge-audio-fetcher.fullname" . }}
spec:
  schedule: {{ .Values.time.schedule | quote }}
  timeZone: {{ .Values.time.timeZone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pilotedge-audio-fetcher
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: pe-audio-volume
                  mountPath: /media/pe-audio
          volumes:
            - name: pe-audio-volume
              persistentVolumeClaim:
               claimName: pvc-pe-audio
          restartPolicy: Never

