apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pilotedge-audio-fetcher.fullname" . }}
spec:
  schedule: {{ .Values.time.schedule | quote }}
  timeZone: {{ .Values.time.timeZone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pilotedge-audio-fetcher
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: OnFailure

