image:
  repository: pilotedge-audio-fetcher
  tag: latest
  pullPolicy: IfNotPresent

storage:
  size: 5Gi

time:
  schedule: "0 1 * * *"
  timeZone: "America/Los_Angeles"

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
